services:
  mysql:
    image: "${DOCKER_IMAGE_NAME}"

    env_file:
      - "${ENV_FILE}"

    command: ["mysqld", "--port=${INTERNAL_PORT}"]

    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"

    restart: ${CONTAINER_RESTART}

    healthcheck:
      test: ["CMD-SHELL", "${HEALTHCHECK_TEST}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      
    volumes:
      - ./mysql:/var/lib/mysql